In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


### Missing value imputation

In [ ]:
#importing the packages
import pandas as pd;
import numpy as np;
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/titanic.csv')

In [ ]:
df.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [ ]:
#printing the number of missing values in the dataset
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
#printing the mean of the Fare
mean = df.Age.mean()
#printing the median of Fare
median = df.Age.median()

In [ ]:
print(mean)
print(median)

29.69911764705882
28.0


In [ ]:
df['Age'].mean()

29.69911764705882

In [ ]:
#imputing missing values of age with mean
df['Age'] = df['Age'].fillna(mean)

In [ ]:
df.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [ ]:
std = df['Age'].std()
std

13.002015226002884

In [ ]:
df.Age.std()

13.002015226002884

In [ ]:
df.shape

(891, 12)

### One hot encoding

In [ ]:
#importing the required packages
import pandas as pd;
import numpy as np;
import matplotlib.pyplot as plt

In [ ]:
#loading the dataset
df = pd.read_csv('/content/drive/MyDrive/titanic.csv')

In [ ]:
df.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [ ]:
#printing the columns of the dataset
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
#printing the unique values of Embarked column
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [ ]:
#converting the categorical variables into numerical variables
pd.get_dummies(df['Sex']).head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [ ]:
pd.get_dummies(df['Embarked']).head()

C  Q  S
0  0  0  1
1  1  0  0
2  0  0  1
3  0  0  1
4  0  0  1

In [ ]:
df.dropna(inplace = True)
# it used to drop null values

In [ ]:
df.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
1             2         1       1  ...  71.2833   C85         C
3             4         1       1  ...  53.1000  C123         S
6             7         0       1  ...  51.8625   E46         S
10           11         1       3  ...  16.7000    G6         S
11           12         1       1  ...  26.5500  C103         S

[5 rows x 12 columns]

In [ ]:
#label encoder
from sklearn.preprocessing import LabelEncoder 

le = LabelEncoder() 

df['Sex']= le.fit_transform(df['Sex']) 
df['Embarked']= le.fit_transform(df['Embarked']) 

In [ ]:
df.head()

PassengerId  Survived  Pclass  ...     Fare  Cabin  Embarked
1             2         1       1  ...  71.2833    C85         0
3             4         1       1  ...  53.1000   C123         2
6             7         0       1  ...  51.8625    E46         2
10           11         1       3  ...  16.7000     G6         2
11           12         1       1  ...  26.5500   C103         2

[5 rows x 12 columns]

### Log transformation

In [ ]:
#logarithmic transformation means replacing each pixel value with it's logarithm value 
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/titanic.csv',usecols =['Age'])

In [ ]:
import numpy as np

df['Age_log']=np.log(df['Age'])
df.head()

Age   Age_log
0  22.0  3.091042
1  38.0  3.637586
2  26.0  3.258097
3  35.0  3.555348
4  35.0  3.555348

### Standardscaler

In [ ]:
#Standardscaler removes the mean and scaling the features to unit variance
import pandas as pd
d = pd.read_csv('/content/drive/MyDrive/titanic.csv') 

In [ ]:
from sklearn.preprocessing import StandardScaler
s = StandardScaler()

In [ ]:
d.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [ ]:
d.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/titanic.csv',usecols =['Pclass','Age','Fare'])

In [ ]:
df1.head()

Pclass   Age     Fare
0       3  22.0   7.2500
1       1  38.0  71.2833
2       3  26.0   7.9250
3       1  35.0  53.1000
4       3  35.0   8.0500

In [ ]:
df_s = s.fit_transform(df1)

In [ ]:
df_s

array([[ 0.82737724, -0.53037664, -0.50244517],
       [-1.56610693,  0.57183099,  0.78684529],
       [ 0.82737724, -0.25482473, -0.48885426],
       ...,
       [ 0.82737724,         nan, -0.17626324],
       [-1.56610693, -0.25482473, -0.04438104],
       [ 0.82737724,  0.15850313, -0.49237783]])

### Minmaxscaler

In [ ]:
#Minmaxscaler brings the each feature to a given range
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()

In [ ]:
d = pd.read_csv('/content/drive/MyDrive/titanic.csv') 

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/titanic.csv',usecols =['Pclass','Age','Fare'])

In [ ]:
df1.head()

Pclass   Age     Fare
0       3  22.0   7.2500
1       1  38.0  71.2833
2       3  26.0   7.9250
3       1  35.0  53.1000
4       3  35.0   8.0500

In [ ]:
df_mm = mm.fit_transform(df1)

In [ ]:
df_mm

array([[1.        , 0.27117366, 0.01415106],
       [0.        , 0.4722292 , 0.13913574],
       [1.        , 0.32143755, 0.01546857],
       ...,
       [1.        ,        nan, 0.04577135],
       [0.        , 0.32143755, 0.0585561 ],
       [1.        , 0.39683338, 0.01512699]])

### RobustScaler

In [ ]:
#Robust scaler uses the statistics that are robust to outliers
#it first removes the outliers and then standardizes the data
import pandas as pd
from sklearn.preprocessing import RobustScaler
r = RobustScaler()

In [ ]:
d = pd.read_csv('/content/drive/MyDrive/titanic.csv') 
df1 = pd.read_csv('/content/drive/MyDrive/titanic.csv',usecols =['Pclass','Age','Fare'])
df1.head()

Pclass   Age     Fare
0       3  22.0   7.2500
1       1  38.0  71.2833
2       3  26.0   7.9250
3       1  35.0  53.1000
4       3  35.0   8.0500

In [ ]:
df_r = r.fit_transform(df1)
df_r

array([[ 0.        , -0.33566434, -0.3120106 ],
       [-2.        ,  0.55944056,  2.46124229],
       [ 0.        , -0.11188811, -0.28277666],
       ...,
       [ 0.        ,         nan,  0.38960398],
       [-2.        , -0.11188811,  0.67328148],
       [ 0.        ,  0.22377622, -0.29035583]])